require: rubocop-rspec

AllCops:
  Exclude:
    - !ruby/regexp /(vendor|bundle|bin|db)\/.*/
    - 'public/uploads/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4.1

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 155

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Metrics/AbcSize:
  Enabled: false

RSpec/DescribedClass:
  Exclude:
    - 'spec/models/concerns/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/api/**/*'

Metrics/BlockLength:
  Max: 182

RSpec/ExampleLength:
  Exclude:
  - 'spec/controllers/answers_controller_spec.rb'
  - 'spec/models/search_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
  - 'spec/controllers/search_controller_spec.rb'
  - 'spec/jobs/question_answer_notification_job_spec.rb'
  - 'spec/jobs/question_digest_job_spec.rb'
  - 'spec/jobs/question_update_notify_job_spec.rb'

Rails/FilePath:
  Exclude:
  - 'config/environments/development.rb'
  - 'spec/factories/attachments.rb'
  - 'spec/features/answers/create_answer_spec.rb'
  - 'spec/features/questions/create_question_spec.rb'
  - 'spec/rails_helper.rb'

Rails/SkipsModelValidations:
  Exclude:
  - 'app/models/answer.rb'

Style/EmptyMethod:
  Enabled: false
