inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - !ruby/regexp /(vendor|bundle|bin|db|sphinxsearch)\/.*/
    - 'public/uploads/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4.1

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 155

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Metrics/AbcSize:
  Enabled: false

RSpec/DescribedClass:
  Exclude:
    - 'spec/models/concerns/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/api/**/*'

Metrics/BlockLength:
  Max: 182

Style/EmptyMethod:
  Enabled: false
