language: ruby
rvm:
  - 2.3.1
  - ruby-head

env:
  - "CHECK='rubocop -D'"

matrix:
  exclude:
    - rvm: ruby-head
      env: "CHECK='rubocop -D'"
  allow_failures:
    - rvm: ruby-head

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: f6f41dcd6b5c35659170071bc801d338bf869ef28faf7e468c894e2645ee878a

services:
  - postgresql

bundler_args: --without development --deployment --jobs=3 --retry=3

before_script:
  - psql -c 'create database stackoverflow_clone_test;' -U postgres
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:setup

gemfile:
  - Gemfile

cache: bundler
