language: ruby
rvm:
  - 2.4.1
  - ruby-head

env:
  - "CHECK='rake'"
  - "CHECK='rubocop -D'"

script: "bundle exec $CHECK"

matrix:
  exclude:
    - rvm: ruby-head
      env: "CHECK='rubocop -D'"
  allow_failures:
    - rvm: ruby-head

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: f6f41dcd6b5c35659170071bc801d338bf869ef28faf7e468c894e2645ee878a

services:
  - postgresql

bundler_args: --without development --deployment --jobs=3 --retry=3

before_script:
  - spec/travis/sphinx-setup.sh
  - psql -c 'create database stackoverflow_clone_test;' -U postgres
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:setup
  - mkdir -p tmp/pids

gemfile:
  - Gemfile

cache: bundler

before_install:
  - "export PHANTOMJS_VERSION=2.1.1"
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"