language: ruby
rvm:
  - 2.4.1
  - ruby-head

env:
  global:
    - CC_TEST_REPORTER_ID=f6f41dcd6b5c35659170071bc801d338bf869ef28faf7e468c894e2645ee878a
  - "CHECK='rake'"
  - "CHECK='rubocop -D'"
script: "bundle exec $CHECK"

matrix:
  exclude:
    - rvm: ruby-head
      env: "CHECK='rubocop -D'"
  allow_failures:
    - rvm: ruby-head

addons:
  postgresql: "9.4"

services:
  - postgresql

bundler_args: --without development --deployment --jobs=3 --retry=3

before_script:
  # cc test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # sphinxsearch
  - sudo bash -c "$(curl -fsSL https://gist.githubusercontent.com/Paprikas/12afff6e9a59f8be2abdf2f564271945/raw/a88b2e34454bbec8f22fbeb2118be15127529f93/install-sphinx)" 2.2.11
  # rails setup
  - psql -c 'create database stackoverflow_clone_test;' -U postgres
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:setup
  - mkdir -p tmp/pids

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

gemfile:
  - Gemfile

cache: bundler

before_install:
  - "export PHANTOMJS_VERSION=2.1.1"
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"